name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.WWW_TOKENS }} # 自己的密匙
        TARGET_REPO: yiruanwang/www    # 自己的仓库地址
        TARGET_BRANCH: gh-pages #这是github默认  你可以自己修改称自己的。但是在pages设置中需要修改
        # BUILD_SCRIPT: yarn && yarn run docs:build
        run: npm install && npm run build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://yr.zhizhu.video  #这里修改成自己的 Custom domain